---
k3s_version: "{{ lookup('env', 'OILSCOPE_K3S_VERSION') | default('v1.32.3+k3s1', true) }}"
k3s_install_script_url: https://get.k3s.io
k3s_install_script_path: /usr/local/lib/oilscope/install-k3s.sh
k3s_server_token_path: /var/lib/rancher/k3s/server/node-token
k3s_server_config_path: /etc/rancher/k3s/config.yaml
