# SPDX-License-Identifier: GPL-2.0-or-later
---
resolve_secrets_config_path: ""
resolve_secrets_project_id: ""

resolve_secrets_metadata_url: >-
  http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token
resolve_secrets_secretmanager_url: https://secretmanager.googleapis.com/v1

resolve_secrets_imds_token_url: http://169.254.169.254/latest/api/token
resolve_secrets_imds_region_url: http://169.254.169.254/latest/meta-data/placement/region

resolve_secrets_awscli_package: awscli
