# SPDX-License-Identifier: GPL-2.0-or-later
---
resolve_secrets_config_path: ""
resolve_secrets_project_id: ""
resolve_secrets_metadata_url: >-
  http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token
resolve_secrets_secretmanager_url: https://secretmanager.googleapis.com/v1
resolve_secrets_aws_cli_path: /usr/local/bin/aws
resolve_secrets_aws_cli_archive: /tmp/oilscope-awscliv2.zip
resolve_secrets_aws_cli_install_dir: /tmp/oilscope-aws-cli
