# SPDX-License-Identifier: GPL-2.0-or-later
---
k3s_traefik_config_file: >-
  {{ project_config_path | default('project-config.json') }}
k3s_traefik_kubeconfig: >-
  {{ lookup('ansible.builtin.env', 'HOME')
     ~ '/.kube/oilscope-'
     ~ k3s_traefik_config.environment
     ~ '.yaml' }}
k3s_traefik_namespace: kube-system
k3s_traefik_helm_chart_config_name: traefik
k3s_traefik_service_name: traefik
k3s_traefik_private_service_name: traefik-private
k3s_traefik_deployment_name: traefik
k3s_traefik_wait_retries: 60
k3s_traefik_wait_delay: 5
k3s_traefik_managed_chart_repository: https://traefik.github.io/charts
k3s_traefik_managed_chart_reference: traefik
k3s_traefik_managed_chart_version: 41.6.0
k3s_traefik_managed_release_name: traefik
k3s_traefik_managed_timeout: 10m0s
k3s_traefik_aws: aws
k3s_traefik_aws_load_balancer_controller_repository: >-
  https://aws.github.io/eks-charts
k3s_traefik_aws_load_balancer_controller_chart: aws-load-balancer-controller
k3s_traefik_aws_load_balancer_controller_chart_version: 1.14.1
k3s_traefik_aws_load_balancer_controller_release_name: >-
  aws-load-balancer-controller
k3s_traefik_aws_load_balancer_controller_service_account: >-
  aws-load-balancer-controller
