# SPDX-License-Identifier: GPL-2.0-or-later
---
fetcher_runtime_environment: >-
  {{
    fetcher_compose_environment
    | combine({
      'DOCKER_CONFIG': fetcher_docker_config_dir,
      'POSTGRES_PASSWORD': fetcher_postgres_password,
      'POSTGRES_USER': fetcher_postgres_user,
      'POSTGRES_DB': fetcher_postgres_name,
      'DATABASE_HOST': fetcher_database_host,
      'DATABASE_PORT': fetcher_database_port | string,
      'DATABASE_SSLMODE': fetcher_database_sslmode,
      'QUEUE_BACKEND': fetcher_queue_backend,
      'AMQP_HOST': fetcher_amqp_host,
      'AMQP_PORT': fetcher_amqp_port | string,
      'RABBITMQ_USER': fetcher_amqp_user,
      'RABBITMQ_VHOST': fetcher_amqp_vhost,
      'RABBITMQ_PASSWORD_URL': fetcher_amqp_password | urlencode,
      'OILPRICEAPI_KEY': fetcher_oilpriceapi_key,
      'FETCHER_BIND_ADDRESS': fetcher_bind_address | string,
      'FETCHER_HOST_PORT': fetcher_host_port | string
    })
  }}
