# SPDX-License-Identifier: GPL-2.0-or-later
---
k3s_secrets_config_file: "{{ project_config_path | default('project-config.json') }}"
k3s_secrets_kubeconfig: >-
  {{ lookup('ansible.builtin.env', 'HOME')
     ~ '/.kube/oilscope-'
     ~ k3s_secrets_config.environment
     ~ '.yaml' }}
k3s_secrets_gcloud: gcloud
k3s_secrets_application_secret_name: "{{ k3s_secrets_config.name_prefix }}-application"
k3s_secrets_registry_secret_name: "{{ k3s_secrets_config.name_prefix }}-registry"
k3s_secrets_registry_server: ghcr.io
