# SPDX-License-Identifier: GPL-2.0-or-later
---
- name: Read the project configuration
  ansible.builtin.set_fact:
    k3s_postgresql_config: >-
      {{ lookup('ansible.builtin.file', k3s_postgresql_config_file) | from_json }}

- name: Install PostgreSQL
  kubernetes.core.helm:
    binary_path: "{{ k3s_postgresql_helm_binary }}"
    release_name: "{{ k3s_postgresql_release_name }}"
    release_namespace: "{{ k3s_postgresql_release_namespace }}"
    chart_ref: "{{ k3s_postgresql_chart_ref }}"
    chart_version: "{{ k3s_postgresql_chart_version }}"
    kubeconfig: "{{ k3s_postgresql_kubeconfig }}"
    values_files:
      - "{{ k3s_postgresql_values_file }}"
    release_values:
      auth:
        existingSecret: "{{ k3s_postgresql_existing_secret }}"
      primary:
        service:
          ports:
            postgresql: "{{ k3s_postgresql_service_port | int }}"
        persistence:
          size: "{{ k3s_postgresql_storage_size }}"
    atomic: true
    wait: true
    timeout: "{{ k3s_postgresql_timeout }}"
