services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 10

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "15672:15672"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 12

  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:  
      POSTGRES_DB: taska-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d taska-db"]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 5s 
    

  backend-service:
    build: ./backend
    container_name: backend-service
    environment:
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_NAME=taska-db
      - DB_USER=admin
      - DB_PASSWORD=admin
      - PORT=5002
    ports:
      - "5002:5002"
    depends_on:
      postgres-db:
        condition: service_healthy   # <-- ключова зміна
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5002/health')"]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 5s

  proxy-service:
    build: ./proxy
    container_name: proxy-service
    environment:
      - BACKEND_SERVICE_URL=http://backend-service:5002
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672/
      - PORT=5001
    depends_on:
      backend-service:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5001/health')"]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 5s 

  poller: 
    build: ./poller-service
    container_name: poller
    environment:
        PROXY_SERVICE_URL: http://proxy-service:5001
        WATCHED_CITIES: "Kyiv,Warsaw,Berlin"
        POLL_INTERVAL_SECONDS: "900"
    depends_on:
         proxy-service:
            condition: service_healthy

  backend-consumer:
    build: ./backend-consumer
    environment:
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_NAME=taska-db
      - DB_USER=admin
      - DB_PASSWORD=admin
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672/
    depends_on:
      postgres-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  ui-service:
    build: ./ui-service
    container_name: ui-service
    environment:
      - PROXY_SERVICE_URL=http://proxy-service:5001
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
       proxy-service:
            condition: service_healthy
       redis:
            condition: service_healthy
    restart: unless-stopped

volumes:
  pgdata:
