# SPDX-License-Identifier: GPL-2.0-or-later
---
k3s_cnpg_operator_config_file: >-
  {{ project_config_path | default('project-config.json') }}
k3s_cnpg_operator_kubeconfig: >-
  {{ lookup('ansible.builtin.env', 'HOME')
     ~ '/.kube/oilscope-'
     ~ k3s_cnpg_operator_config.environment
     ~ '.yaml' }}
k3s_cnpg_operator_values_file: >-
  {{ lookup('ansible.builtin.env', 'PWD')
     ~ '/infrastructure/kubernetes/values/cloudnative-pg.yaml' }}
k3s_cnpg_operator_helm_binary: helm
k3s_cnpg_operator_release_name: cloudnative-pg
k3s_cnpg_operator_release_namespace: cnpg-system
k3s_cnpg_operator_chart_ref: >-
  oci://ghcr.io/cloudnative-pg/charts/cloudnative-pg
k3s_cnpg_operator_chart_version: "0.29.1"
k3s_cnpg_operator_timeout: 10m0s
