# SPDX-License-Identifier: GPL-2.0-or-later
---

# handlers file for k3s
- name: Restart k3s
  become: true
  ansible.builtin.systemd_service:
    name: "{{ 'k3s' if k3s_role == 'server' else 'k3s-agent' }}"
    state: restarted
