bind 0.0.0.0
protected-mode yes
port 6379
tcp-backlog 128
timeout 0
tcp-keepalive 300
daemonize no
loglevel notice
logfile ""
databases 1

aclfile /usr/local/etc/redis/users.acl

save 900 1
save 300 10
stop-writes-on-bgsave-error no
rdbcompression yes
dbfilename dump.rdb
dir /data
appendonly no

maxmemory 128mb
maxmemory-policy allkeys-lru

rename-command FLUSHALL ""
rename-command FLUSHDB ""
rename-command CONFIG ""
rename-command DEBUG ""
rename-command SHUTDOWN ""
