"""Ukrainian animal names resolved only by the Fetcher service."""


ANIMAL_NAMES = {
    # Mammals
    "вовк": "Canis lupus",
    "лисиця": "Vulpes vulpes",
    "лисиця руда": "Vulpes vulpes",
    "рись": "Lynx lynx",
    "рись євразійська": "Lynx lynx",
    "зубр": "Bison bonasus",
    "видра": "Lutra lutra",
    "видра річкова": "Lutra lutra",
    "лось": "Alces alces",
    "олень": "Cervus elaphus",
    "олень благородний": "Cervus elaphus",
    "олень плямистий": "Cervus nippon",
    "козуля": "Capreolus capreolus",
    "козуля європейська": "Capreolus capreolus",
    "кабан": "Sus scrofa",
    "дикий кабан": "Sus scrofa",
    "ведмідь": "Ursus arctos",
    "бурий ведмідь": "Ursus arctos",
    "шакал": "Canis aureus",
    "шакал золотистий": "Canis aureus",
    "кіт лісовий": "Felis silvestris",
    "борсук": "Meles meles",
    "борсук європейський": "Meles meles",
    "бобер": "Castor fiber",
    "бобер європейський": "Castor fiber",
    "заєць": "Lepus europaeus",
    "заєць сірий": "Lepus europaeus",
    "білка": "Sciurus vulgaris",
    "білка звичайна": "Sciurus vulgaris",
    "їжак": "Erinaceus roumanicus",
    "їжак білочеревий": "Erinaceus roumanicus",
    "бабак": "Marmota bobak",
    "бабак степовий": "Marmota bobak",
    "хом'як": "Cricetus cricetus",
    "хом'як звичайний": "Cricetus cricetus",
    "ондатра": "Ondatra zibethicus",
    "кріт": "Talpa europaea",
    "кріт європейський": "Talpa europaea",
    "куниця лісова": "Martes martes",
    "куниця кам'яна": "Martes foina",
    "тхір лісовий": "Mustela putorius",
    "тхір степовий": "Mustela eversmanii",
    "норка європейська": "Mustela lutreola",
    "норка американська": "Neogale vison",
    "горностай": "Mustela erminea",
    "ласка": "Mustela nivalis",
    "єнотоподібний собака": "Nyctereutes procyonoides",
    "єнот": "Procyon lotor",
    "лань": "Dama dama",
    "муфлон": "Ovis musimon",
    "кролик дикий": "Oryctolagus cuniculus",
    "ховрах європейський": "Spermophilus citellus",
    "полівка руда": "Myodes glareolus",
    "полівка темна": "Microtus agrestis",
    "полівка водяна": "Arvicola amphibius",
    "миша польова": "Apodemus agrarius",
    "миша жовтогорла": "Apodemus flavicollis",
    "миша хатня": "Mus musculus",
    "мишка лучна": "Micromys minutus",
    "пацюк сірий": "Rattus norvegicus",
    "пацюк чорний": "Rattus rattus",
    "сліпак малий": "Nannospalax leucodon",
    "бурозубка звичайна": "Sorex araneus",
    "бурозубка мала": "Sorex minutus",
    "рясоніжка велика": "Neomys fodiens",
    "вечірниця руда": "Nyctalus noctula",
    "нетопир карлик": "Pipistrellus pipistrellus",
    "нічниця велика": "Myotis myotis",
    "нічниця ставкова": "Myotis dasycneme",
    "підковик малий": "Rhinolophus hipposideros",
    "підковик великий": "Rhinolophus ferrumequinum",
    "дельфін білобокий": "Delphinus delphis",
    "афаліна": "Tursiops truncatus",
    "морська свиня": "Phocoena phocoena",

    # Birds
    "лелека білий": "Ciconia ciconia",
    "лелека чорний": "Ciconia nigra",
    "журавель сірий": "Grus grus",
    "пелікан рожевий": "Pelecanus onocrotalus",
    "пелікан кучерявий": "Pelecanus crispus",
    "баклан великий": "Phalacrocorax carbo",
    "чапля сіра": "Ardea cinerea",
    "чепура велика": "Ardea alba",
    "чепура мала": "Egretta garzetta",
    "бугай": "Botaurus stellaris",
    "косар": "Platalea leucorodia",
    "фламінго рожевий": "Phoenicopterus roseus",
    "лебідь": "Cygnus olor",
    "лебідь-шипун": "Cygnus olor",
    "лебідь-кликун": "Cygnus cygnus",
    "крижень": "Anas platyrhynchos",
    "качка крижень": "Anas platyrhynchos",
    "чирянка мала": "Anas crecca",
    "чирянка велика": "Spatula querquedula",
    "нерозень": "Mareca strepera",
    "свищ": "Mareca penelope",
    "попелюх": "Aythya ferina",
    "чернь чубата": "Aythya fuligula",
    "гоголь": "Bucephala clangula",
    "крех великий": "Mergus merganser",
    "гуска сіра": "Anser anser",
    "гуска білолоба": "Anser albifrons",
    "гуменник": "Anser fabalis",
    "казарка червоновола": "Branta ruficollis",
    "галагаз": "Tadorna tadorna",
    "орлан-білохвіст": "Haliaeetus albicilla",
    "беркут": "Aquila chrysaetos",
    "орел-могильник": "Aquila heliaca",
    "підорлик малий": "Clanga pomarina",
    "шуліка чорний": "Milvus migrans",
    "яструб великий": "Accipiter gentilis",
    "яструб малий": "Accipiter nisus",
    "лунь очеретяний": "Circus aeruginosus",
    "лунь польовий": "Circus cyaneus",
    "канюк звичайний": "Buteo buteo",
    "сапсан": "Falco peregrinus",
    "боривітер звичайний": "Falco tinnunculus",
    "підсоколик великий": "Falco subbuteo",
    "пугач": "Bubo bubo",
    "сова сіра": "Strix aluco",
    "сова вухата": "Asio otus",
    "сич хатній": "Athene noctua",
    "сипуха": "Tyto alba",
    "перепілка": "Coturnix coturnix",
    "тетерук": "Lyrurus tetrix",
    "глушець": "Tetrao urogallus",
    "фазан звичайний": "Phasianus colchicus",
    "куріпка сіра": "Perdix perdix",
    "пірникоза велика": "Podiceps cristatus",
    "пірникоза мала": "Tachybaptus ruficollis",
    "лиска": "Fulica atra",
    "курочка водяна": "Gallinula chloropus",
    "деркач": "Crex crex",
    "чайка": "Vanellus vanellus",
    "баранець звичайний": "Gallinago gallinago",
    "слуква": "Scolopax rusticola",
    "кульон великий": "Numenius arquata",
    "кулик-довгоніг": "Himantopus himantopus",
    "мартин звичайний": "Chroicocephalus ridibundus",
    "мартин сріблястий": "Larus argentatus",
    "мартин жовтоногий": "Larus cachinnans",
    "крячок річковий": "Sterna hirundo",
    "голуб сизий": "Columba livia",
    "припутень": "Columba palumbus",
    "горлиця садова": "Streptopelia decaocto",
    "горлиця звичайна": "Streptopelia turtur",
    "зозуля звичайна": "Cuculus canorus",
    "одуд": "Upupa epops",
    "рибалочка блакитний": "Alcedo atthis",
    "бджолоїдка звичайна": "Merops apiaster",
    "дятел звичайний": "Dendrocopos major",
    "дятел великий строкатий": "Dendrocopos major",
    "дятел сирійський": "Dendrocopos syriacus",
    "жовна зелена": "Picus viridis",
    "жовна чорна": "Dryocopus martius",
    "жайворонок польовий": "Alauda arvensis",
    "ластівка сільська": "Hirundo rustica",
    "плиска біла": "Motacilla alba",
    "плиска жовта": "Motacilla flava",
    "вільшанка": "Erithacus rubecula",
    "соловейко східний": "Luscinia luscinia",
    "горихвістка чорна": "Phoenicurus ochruros",
    "горихвістка звичайна": "Phoenicurus phoenicurus",
    "кам'янка звичайна": "Oenanthe oenanthe",
    "дрізд чорний": "Turdus merula",
    "дрізд співочий": "Turdus philomelos",
    "чикотень": "Turdus pilaris",
    "дрізд білобровий": "Turdus iliacus",
    "очеретянка велика": "Acrocephalus arundinaceus",
    "вівчарик-ковалик": "Phylloscopus collybita",
    "вівчарик весняний": "Phylloscopus trochilus",
    "мухоловка сіра": "Muscicapa striata",
    "мухоловка строката": "Ficedula hypoleuca",
    "синиця велика": "Parus major",
    "синиця блакитна": "Cyanistes caeruleus",
    "синиця болотяна": "Poecile palustris",
    "синиця довгохвоста": "Aegithalos caudatus",
    "повзик": "Sitta europaea",
    "підкоришник звичайний": "Certhia familiaris",
    "волове очко": "Troglodytes troglodytes",
    "зяблик": "Fringilla coelebs",
    "щиглик": "Carduelis carduelis",
    "зеленяк": "Chloris chloris",
    "снігур": "Pyrrhula pyrrhula",
    "костогриз": "Coccothraustes coccothraustes",
    "вівсянка звичайна": "Emberiza citrinella",
    "вівсянка очеретяна": "Emberiza schoeniclus",
    "горобець хатній": "Passer domesticus",
    "шпак": "Sturnus vulgaris",
    "сойка": "Garrulus glandarius",
    "сорока": "Pica pica",
    "ворона сіра": "Corvus cornix",
    "грак": "Corvus frugilegus",
    "крук": "Corvus corax",

    # Reptiles and amphibians
    "вуж звичайний": "Natrix natrix",
    "вуж водяний": "Natrix tessellata",
    "мідянка звичайна": "Coronella austriaca",
    "полоз ескулапів": "Zamenis longissimus",
    "полоз жовточеревий": "Dolichophis caspius",
    "гадюка звичайна": "Vipera berus",
    "гадюка нікольського": "Vipera nikolskii",
    "гадюка степова": "Vipera renardi",
    "ящірка прудка": "Lacerta agilis",
    "ящірка зелена": "Lacerta viridis",
    "ящірка живородна": "Zootoca vivipara",
    "веретільниця ламка": "Anguis fragilis",
    "черепаха болотяна": "Emys orbicularis",
    "ропуха сіра": "Bufo bufo",
    "ропуха зелена": "Bufotes viridis",
    "жаба озерна": "Pelophylax ridibundus",
    "жаба ставкова": "Pelophylax lessonae",
    "жаба їстівна": "Pelophylax esculentus",
    "жаба трав'яна": "Rana temporaria",
    "жаба гостроморда": "Rana arvalis",
    "райка східна": "Hyla orientalis",
    "кумка червоночерева": "Bombina bombina",
    "кумка жовточерева": "Bombina variegata",
    "часничниця звичайна": "Pelobates fuscus",
    "тритон звичайний": "Lissotriton vulgaris",
    "тритон карпатський": "Lissotriton montandoni",
    "тритон гребінчастий": "Triturus cristatus",
    "саламандра плямиста": "Salamandra salamandra",

    # Fish
    "щука": "Esox lucius",
    "сом європейський": "Silurus glanis",
    "короп": "Cyprinus carpio",
    "сазан": "Cyprinus carpio",
    "окунь річковий": "Perca fluviatilis",
    "судак звичайний": "Sander lucioperca",
    "карась сріблястий": "Carassius gibelio",
    "карась звичайний": "Carassius carassius",
    "плітка": "Rutilus rutilus",
    "лящ": "Abramis brama",
    "верховодка": "Alburnus alburnus",
    "в'язь": "Leuciscus idus",
    "головень": "Squalius cephalus",
    "білизна": "Aspius aspius",
    "марена звичайна": "Barbus barbus",
    "лин": "Tinca tinca",
    "краснопірка": "Scardinius erythrophthalmus",
    "пічкур звичайний": "Gobio gobio",
    "амур білий": "Ctenopharyngodon idella",
    "товстолоб білий": "Hypophthalmichthys molitrix",
    "товстолоб строкатий": "Hypophthalmichthys nobilis",
    "минь річковий": "Lota lota",
    "йорж звичайний": "Gymnocephalus cernua",
    "вугор європейський": "Anguilla anguilla",
    "форель струмкова": "Salmo trutta",
    "форель райдужна": "Oncorhynchus mykiss",
    "лосось атлантичний": "Salmo salar",
    "лосось дунайський": "Hucho hucho",
    "стерлядь": "Acipenser ruthenus",
    "осетер російський": "Acipenser gueldenstaedtii",
    "білуга": "Huso huso",
    "тюлька чорноморська": "Clupeonella cultriventris",
    "хамса європейська": "Engraulis encrasicolus",
    "бичок-кругляк": "Neogobius melanostomus",
    "бичок-пісочник": "Neogobius fluviatilis",

    # Insects and other invertebrates
    "бджола медоносна": "Apis mellifera",
    "джміль земляний": "Bombus terrestris",
    "шершень європейський": "Vespa crabro",
    "оса звичайна": "Vespula vulgaris",
    "мурашка руда лісова": "Formica rufa",
    "сонечко семикрапкове": "Coccinella septempunctata",
    "сонечко двокрапкове": "Adalia bipunctata",
    "сонечко азійське": "Harmonia axyridis",
    "жук-олень": "Lucanus cervus",
    "жук-носоріг": "Oryctes nasicornis",
    "жук бронзівка золотиста": "Cetonia aurata",
    "хрущ травневий": "Melolontha melolontha",
    "турун шкірястий": "Carabus coriaceus",
    "колорадський жук": "Leptinotarsa decemlineata",
    "махаон": "Papilio machaon",
    "подалірій": "Iphiclides podalirius",
    "адмірал": "Vanessa atalanta",
    "сонцевик будяковий": "Vanessa cardui",
    "павиче око денне": "Aglais io",
    "кропив'янка": "Aglais urticae",
    "цитринець": "Gonepteryx rhamni",
    "білан капустяний": "Pieris brassicae",
    "мінливець великий": "Apatura iris",
    "сатурнія велика": "Saturnia pyri",
    "язикан звичайний": "Macroglossum stellatarum",
    "богомол звичайний": "Mantis religiosa",
    "коник зелений": "Tettigonia viridissima",
    "цвіркун польовий": "Gryllus campestris",
    "капустянка звичайна": "Gryllotalpa gryllotalpa",
    "вуховертка звичайна": "Forficula auricularia",
    "коромисло синє": "Aeshna cyanea",
    "бабка плоска": "Libellula depressa",
    "красуня блискуча": "Calopteryx splendens",
    "муха хатня": "Musca domestica",
    "муха зелена": "Lucilia sericata",
    "комар звичайний": "Culex pipiens",
    "павук-хрестовик": "Araneus diadematus",
    "аргіопа тигрова": "Argiope bruennichi",
    "равлик виноградний": "Helix pomatia",
    "слимак іспанський": "Arion vulgaris",
    "рак річковий широкопалий": "Astacus astacus",
}
