"""initial schema

Revision ID: fdb8606f091f
Revises: 
Create Date: 2026-07-20 15:48:26.989182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdb8606f091f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('latitude', 'longitude', name='uq_locations_lat_lon')
    )
    op.create_table('current_weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('apparent_temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('precipitation', sa.Float(), nullable=False),
    sa.Column('weather_code', sa.Integer(), nullable=False),
    sa.Column('cloud_cover', sa.Float(), nullable=False),
    sa.Column('wind_speed', sa.Float(), nullable=False),
    sa.Column('wind_direction', sa.Float(), nullable=False),
    sa.Column('surface_pressure', sa.Float(), nullable=False),
    sa.Column('is_day', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('synchronized_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', name='uq_current_weather_location')
    )
    op.create_table('daily_weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('weather_date', sa.Date(), nullable=False),
    sa.Column('weather_code', sa.Integer(), nullable=False),
    sa.Column('temperature_max', sa.Float(), nullable=False),
    sa.Column('temperature_min', sa.Float(), nullable=False),
    sa.Column('apparent_temperature_max', sa.Float(), nullable=False),
    sa.Column('apparent_temperature_min', sa.Float(), nullable=False),
    sa.Column('sunrise', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sunset', sa.DateTime(timezone=True), nullable=False),
    sa.Column('precipitation_sum', sa.Float(), nullable=False),
    sa.Column('rain_sum', sa.Float(), nullable=False),
    sa.Column('snowfall_sum', sa.Float(), nullable=False),
    sa.Column('precipitation_hours', sa.Float(), nullable=False),
    sa.Column('wind_speed_max', sa.Float(), nullable=False),
    sa.Column('wind_gusts_max', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('synchronized_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'weather_date', name='uq_daily_weather_location_date')
    )
    op.create_table('hourly_weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('weather_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('apparent_temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('precipitation_probability', sa.Float(), nullable=True),
    sa.Column('precipitation', sa.Float(), nullable=False),
    sa.Column('weather_code', sa.Integer(), nullable=False),
    sa.Column('cloud_cover', sa.Float(), nullable=False),
    sa.Column('visibility', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=False),
    sa.Column('wind_direction', sa.Float(), nullable=False),
    sa.Column('synchronized_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'weather_time', name='uq_hourly_weather_location_time')
    )
    op.create_table('weather_syncs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('in_progress', 'success', 'failed', 'skipped', name='syncstatus', native_enum=False, length=20), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('trigger_type', sa.Enum('startup', 'scheduler', 'internal_endpoint', name='triggertype', native_enum=False, length=30), nullable=False),
    sa.Column('open_meteo_request_url', sa.String(length=500), nullable=True),
    sa.Column('open_meteo_status_code', sa.Integer(), nullable=True),
    sa.Column('open_meteo_duration_ms', sa.Integer(), nullable=True),
    sa.Column('records_received', sa.Integer(), nullable=True),
    sa.Column('daily_records_received', sa.Integer(), nullable=True),
    sa.Column('hourly_records_received', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_syncs')
    op.drop_table('hourly_weather')
    op.drop_table('daily_weather')
    op.drop_table('current_weather')
    op.drop_table('locations')
    # ### end Alembic commands ###
