name: backend-service

services:
  backend-service:
    build: ../../backend-service
    restart: unless-stopped
    logging:
      driver: journald

    environment:
      APP_HOST: "0.0.0.0"
      APP_PORT: "5001"
      FLASK_DEBUG: "false"

      DATABASE_URL: "postgresql://weather_user:weather_password@${DATABASE_IP}:5432/weather_history"

      PROVIDER_URL: "http://${PROVIDER_IP}:5002"

      RABBITMQ_URL: "amqp://weather_user:weather_password@${DATABASE_IP}:5672/"

    ports:
      - "5001:5001"

    healthcheck:
      test:
        - CMD
        - python3
        - -c
        - >-
          import urllib.request;
          urllib.request.urlopen(
          'http://127.0.0.1:5001/health',
          timeout=3
          )
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
