# SPDX-License-Identifier: GPL-2.0-or-later
---
# Collections required by the OilScope multi-cloud dynamic inventory.
collections:
  - name: google.cloud
    version: ">=1.14.0"

  - name: amazon.aws
    version: ">=11.4.0"
