---
- name: Create the application namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: oilscope

- name: Provision application secrets
  ansible.builtin.import_tasks: secrets.yaml

- name: Provision the PostgreSQL cluster
  ansible.builtin.import_tasks: database.yaml

- name: Deploy the application chart
  kubernetes.core.helm:
    name: oilscope
    chart_ref: "{{ role_path }}/files/oilscope"
    release_namespace: oilscope
    create_namespace: false
    wait: false
    values:
      image:
        repository: "{{ k8s_app_config.registry.repository }}"
        tag: "{{ k8s_app_config.registry.image_sha }}"
      ui:
        ingress:
          host: "{{ k8s_app_public_endpoint.hostname }}"
      migrate:
        pgHost: "{{ k8s_app_db_host }}"