---
- name: Install cert-manager
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: "oci://quay.io/jetstack/charts/cert-manager"
    chart_version: "{{ cert_manager_version }}"
    release_namespace: cert-manager
    create_namespace: true
    values:
      crds:
        enabled: true
    wait: true

- name: Create the Cloudflare API token secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: cloudflare-api-token
        namespace: cert-manager
      type: Opaque
      data:
        api-token: "{{ cloudflare_api_token | b64encode }}"
  no_log: true

- name: Create the Let's Encrypt ClusterIssuer
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: letsencrypt-prod
      spec:
        acme:
          server: https://acme-v02.api.letsencrypt.org/directory
          email: "{{ k8s_app_public_endpoint.acme_email }}"
          privateKeySecretRef:
            name: letsencrypt-prod-account-key
          solvers:
            - dns01:
                cloudflare:
                  apiTokenSecretRef:
                    name: cloudflare-api-token
                    key: api-token