---
- name: Ensure the local kubeconfig directory exists
  ansible.builtin.file:
    path: "{{ k8s_local_kubeconfig | dirname }}"
    state: directory
    mode: "0700"

- name: Write a kubeconfig for the k3s cluster
  ansible.builtin.import_tasks: kubeconfig_k3s.yaml
  when: not k8s_app_managed | bool

- name: Write a kubeconfig for the managed cluster
  ansible.builtin.import_tasks: kubeconfig_managed.yaml
  when: k8s_app_managed | bool
