# SPDX-License-Identifier: MIT-0
---
compose_project_templates:
  rabbitmq: compose.rabbitmq.yaml.j2
  redis: compose.redis.yaml.j2
  history: compose.history.yaml.j2
  fetcher: compose.fetcher.yaml.j2
  ui: compose.ui.yaml.j2
  proxy: compose.proxy.yaml.j2
