# SPDX-License-Identifier: GPL-2.0-or-later
---
- name: Restart Google Cloud Ops Agent
  ansible.builtin.service:
    name: google-cloud-ops-agent
    state: restarted

- name: Reload Amazon CloudWatch Agent configuration
  ansible.builtin.command:
    argv:
      - /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl
      - -a
      - fetch-config
      - -m
      - ec2
      - -s
      - -c
      - file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
  changed_when: true
