download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/google-cloud-1.14.0.tar.gz
format_version: 1.0.0
name: cloud
namespace: google
server: https://galaxy.ansible.com/api/
signatures: []
version: 1.14.0
version_url: /api/content/published/v3/plugin/ansible/content/published/collections/index/google/cloud/versions/1.14.0/
