image:
  digest: sha256:720413b8e463ee8ae3bad7d3ac99a17eb66b7d448738c6256cba91e2388dcde8

architecture: standalone

auth:
  enablePostgresUser: false
  username: oil_tracker
  database: oil_tracker
  secretKeys:
    userPasswordKey: POSTGRES_PASSWORD
  usePasswordFiles: true

primary:
  service:
    type: ClusterIP
  persistence:
    enabled: true
    storageClass: local-path
    accessModes:
      - ReadWriteOnce
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

metrics:
  enabled: false
