"""add daily_forecast table and weather_syncs.forecast_records_received

Revision ID: 2d99cab83354
Revises: afadc76e3e6a
Create Date: 2026-07-23 18:31:03.392218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d99cab83354'
down_revision: Union[str, Sequence[str], None] = 'afadc76e3e6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_forecast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('weather_date', sa.Date(), nullable=False),
    sa.Column('weather_code', sa.Integer(), nullable=False),
    sa.Column('temperature_min', sa.Float(), nullable=False),
    sa.Column('temperature_max', sa.Float(), nullable=False),
    sa.Column('apparent_temperature_min', sa.Float(), nullable=False),
    sa.Column('apparent_temperature_max', sa.Float(), nullable=False),
    sa.Column('precipitation_probability_max', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('synchronized_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'weather_date', name='uq_daily_forecast_location_date')
    )
    op.add_column('weather_syncs', sa.Column('forecast_records_received', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather_syncs', 'forecast_records_received')
    op.drop_table('daily_forecast')
    # ### end Alembic commands ###
