# SPDX-License-Identifier: GPL-2.0-or-later
---
monitoring_agent_enabled: "{{ oilscope_config.monitoring.enabled | bool }}"
monitoring_agent_interval_seconds: >-
  {{ oilscope_config.monitoring.metrics_interval_seconds | int }}

monitoring_agent_aws_package_path: /tmp/amazon-cloudwatch-agent.deb
monitoring_agent_aws_package_base_url: >-
  https://amazoncloudwatch-agent.s3.amazonaws.com/ubuntu
monitoring_agent_aws_config_path: >-
  /opt/aws/amazon-cloudwatch-agent/etc/oilscope.json
monitoring_agent_aws_prometheus_config_path: >-
  /opt/aws/amazon-cloudwatch-agent/etc/prometheus.yaml
monitoring_agent_aws_architectures:
  x86_64: amd64
  aarch64: arm64

monitoring_agent_gcp_install_script_path: >-
  /tmp/add-google-cloud-ops-agent-repo.sh
monitoring_agent_gcp_install_script_url: >-
  https://dl.google.com/cloudagents/add-google-cloud-ops-agent-repo.sh
monitoring_agent_gcp_config_path: /etc/google-cloud-ops-agent/config.yaml
