# SPDX-License-Identifier: GPL-2.0-or-later
---
registry_auth_registry: ghcr.io
registry_auth_username: "{{ lookup('ansible.builtin.env', 'GHCR_USERNAME') }}"
registry_auth_token: "{{ lookup('ansible.builtin.env', 'GHCR_TOKEN') }}"
registry_auth_docker_config_dir: /run/oilscope/docker-auth
