# SPDX-License-Identifier: GPL-2.0-or-later
---
- name: Configure AWS observability
  hosts: aws
  become: true
  gather_facts: false
  force_handlers: true
  any_errors_fatal: true
  roles:
    - role: oilscope.platform.aws_cloudwatch_agent
