# SPDX-License-Identifier: GPL-2.0-or-later
---
- name: Configure GCP observability
  hosts: gcp
  become: true
  gather_facts: false
  force_handlers: true
  any_errors_fatal: true
  roles:
    - role: oilscope.platform.gcp_ops_agent
