# SPDX-License-Identifier: GPL-2.0-or-later
---
- name: Configure access to the managed Kubernetes cluster
  hosts: localhost
  connection: local
  gather_facts: false
  any_errors_fatal: true
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  roles:
    - role: oilscope.platform.managed_kubernetes_kubeconfig
