# SPDX-License-Identifier: GPL-2.0-or-later
---
- name: Configure and verify cross-cloud private networking
  ansible.builtin.import_playbook: tailscale.yml

- name: Configure cloud monitoring agents
  ansible.builtin.import_playbook: monitoring_agents.yml

- name: Configure the K3s cluster and deploy Kubernetes workloads
  ansible.builtin.import_playbook: k3s_cluster.yml

- name: Deploy Database workload
  ansible.builtin.import_playbook: database.yml

- name: Deploy History workload
  ansible.builtin.import_playbook: history.yml

- name: Deploy Fetcher workload
  ansible.builtin.import_playbook: fetcher.yml

- name: Deploy UI workload
  ansible.builtin.import_playbook: ui.yml
