# SPDX-License-Identifier: GPL-2.0-or-later
---
- name: Deploy K3s add-ons
  hosts: localhost
  connection: local
  gather_facts: false
  any_errors_fatal: true
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    k3s_addons_config_file: "{{ project_config_path | default('project-config.json') }}"
  roles:
    - role: oilscope.platform.k3s_cert_manager
      vars:
        k3s_cert_manager_config_file: "{{ k3s_addons_config_file }}"
    - role: oilscope.platform.k3s_postgresql
      vars:
        k3s_postgresql_config_file: "{{ k3s_addons_config_file }}"
    - role: oilscope.platform.k3s_rabbitmq
      vars:
        k3s_rabbitmq_config_file: "{{ k3s_addons_config_file }}"
    - role: oilscope.platform.k3s_redis
      vars:
        k3s_redis_config_file: "{{ k3s_addons_config_file }}"
