# SPDX-License-Identifier: GPL-2.0-or-later
---
- name: Deploy UI
  hosts: ui
  become: true
  gather_facts: true
  roles:
    - role: oilscope.platform.host_baseline

    - role: oilscope.platform.docker_engine

    - role: oilscope.platform.compose_project
      vars:
        compose_project_config_path: "{{ project_config_path }}"
        compose_project_workload: "{{ oilscope_role }}"

    - role: oilscope.platform.resolve_secrets
      vars:
        resolve_secrets_config_path: "{{ project_config_path }}"
        resolve_secrets_workload: "{{ oilscope_role }}"

    - role: oilscope.platform.ui
      vars:
        ui_application_image_tag: >-
          {{ compose_project_config.registry.image_sha }}
        ui_postgres_image: >-
          {{
            compose_project_config.registry.repository
            ~ '/database:'
            ~ compose_project_config.registry.image_sha
          }}
        ui_postgres_password: "{{ resolve_secrets_result.POSTGRES_PASSWORD }}"
