# SPDX-License-Identifier: GPL-2.0-or-later
---
galaxy_info:
  author: Zoia Holubkova
  description: Run the OilScope services in the cluster and publish the UI over HTTPS
  license: GPL-2.0-or-later
  min_ansible_version: "2.16"
  galaxy_tags:
    - kubernetes

dependencies: []
