# SPDX-License-Identifier: GPL-2.0-or-later
---
plugin: google.cloud.gcp_compute

projects:
  - example-project-12345

zones:
  - europe-west1-b

filters:
  - labels.application = oilscope
  - labels.environment = dev

auth_kind: application

hostnames:
  - name

vars_prefix: gcp_

keyed_groups:
  - key: labels.role
    prefix: ""
    separator: ""

groups:
  workloads: labels.role is defined and labels.role != 'bastion'

compose:
  internal_ip: networkInterfaces[0].networkIP
  public_ip: >-
    networkInterfaces[0].accessConfigs[0].natIP
    if networkInterfaces[0].accessConfigs | default([])
    else ''

  ansible_host: >-
    networkInterfaces[0].accessConfigs[0].natIP
    if labels.role | default('') == 'bastion'
    else networkInterfaces[0].networkIP

  oilscope_role: labels.role | default('')

cache: true
cache_plugin: ansible.builtin.jsonfile
cache_connection: ~/.cache/oilscope-inventory
cache_timeout: 300
