# SPDX-License-Identifier: GPL-2.0-or-later
---
galaxy_info:
  author: Push and Pray team
  description: Secure SSH access through the OilScope bastion
  license: GPL-2.0-or-later
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - bastion
    - infrastructure
    - ssh

dependencies: []
