# SPDX-License-Identifier: GPL-2.0-or-later
---
galaxy_info:
  author: Push and Pray team
  description: Deploy RabbitMQ on the former database VM in managed database mode
  license: GPL-2.0-or-later
  min_ansible_version: "2.16"
  galaxy_tags:
    - docker
    - messaging
    - rabbitmq

dependencies: []
