{{- if .Values.ui.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ui
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ui.ingress.clusterIssuer }}
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - {{ .Values.ui.ingress.host | quote }}
      secretName: {{ .Values.ui.ingress.tlsSecret }}
  rules:
    - host: {{ .Values.ui.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ui
                port:
                  name: http
{{- end }}