resource "local_file" "ansible_inventory" {
  filename        = "${path.module}/../ansible/inventory.ini"
  file_permission = "0644"

  content = <<-EOT
# Auto-generated by Terraform — do not edit manually.
# Re-run `terraform apply` to refresh after infrastructure changes.

[bastion]
bastion ansible_host=${module.vm["bastion"].public_ip} ansible_port=${local.bastion_vm.ssh_port}

[database]
infra ansible_host=${module.vm["infra"].internal_ip}

[history]
history ansible_host=${module.vm["history"].internal_ip}

[fetcher]
fetcher ansible_host=${module.vm["fetcher"].internal_ip}

[ui]
ui ansible_host=${module.vm["ui"].internal_ip}

[workloads:children]
database
history
fetcher
ui

[all:vars]
ansible_user=${local.config.admin_ssh_user}
ansible_ssh_private_key_file=~/.ssh/gcp-academy
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[workloads:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyJump=${local.config.admin_ssh_user}@${module.vm["bastion"].public_ip}:${local.bastion_vm.ssh_port}'
  EOT
}
