# SPDX-License-Identifier: MIT-0
---
galaxy_info:
  author: Push and Pray team
  description: Install and configure the cloud-native VM monitoring agent
  license: MIT-0
  min_ansible_version: "2.21"
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - infrastructure
    - monitoring

dependencies: []
