---
managed_database_migration_enabled: false
managed_database_migration_image: ""
managed_database_migration_connection: {}
managed_database_migration_password: ""
managed_database_migration_docker_config_dir: /run/oilscope/docker-auth
