# SPDX-License-Identifier: GPL-2.0-or-later
---
k3s_api_oidc_enabled: false
k3s_api_oidc_config_dir: /etc/rancher/k3s/config.yaml.d
k3s_api_oidc_config_path: /etc/rancher/k3s/config.yaml.d/10-oidc.yaml
k3s_api_oidc_binary_path: /usr/local/bin/k3s
k3s_api_oidc_username_claim: email
k3s_api_oidc_username_prefix: "oidc:"
k3s_api_oidc_groups_claim: ""
k3s_api_oidc_groups_prefix: "oidc:"
k3s_api_oidc_ready_timeout: 300
