# SPDX-License-Identifier: MIT-0
---
# defaults file for host_baseline
host_baseline_deploy_user: deploy
host_baseline_deploy_group: deploy

host_baseline_packages:
  - ca-certificates
  - curl
  - jq

host_baseline_cloudwatch_agent_package_path: >-
  /var/cache/apt/archives/amazon-cloudwatch-agent.deb
host_baseline_cloudwatch_agent_architecture: >-
  {{ 'arm64' if ansible_architecture in ['aarch64', 'arm64'] else 'amd64' }}
host_baseline_cloudwatch_agent_url: >-
  https://amazoncloudwatch-agent-{{ oilscope_region }}.s3.{{ oilscope_region }}.amazonaws.com/ubuntu/{{ host_baseline_cloudwatch_agent_architecture }}/latest/amazon-cloudwatch-agent.deb
host_baseline_ops_agent_install_script_path: /usr/local/src/add-google-cloud-ops-agent-repo.sh
host_baseline_ops_agent_install_script_url: >-
  https://dl.google.com/cloudagents/add-google-cloud-ops-agent-repo.sh

host_baseline_directories:
  - path: /opt/oilscope
    owner: root
    group: root
    mode: "0755"

  - path: /opt/oilscope/app
    owner: "{{ host_baseline_deploy_user }}"
    group: "{{ host_baseline_deploy_group }}"
    mode: "0750"

  - path: /opt/oilscope/deploy
    owner: "{{ host_baseline_deploy_user }}"
    group: "{{ host_baseline_deploy_group }}"
    mode: "0750"

  - path: /var/lib/oilscope
    owner: "{{ host_baseline_deploy_user }}"
    group: "{{ host_baseline_deploy_group }}"
    mode: "0750"
