# SPDX-License-Identifier: GPL-2.0-or-later
---
ui_compose_project_dir: /opt/oilscope/app
ui_compose_file: "{{ ui_compose_project_dir }}/compose.yaml"
ui_compose_project_name: oilscope

ui_redis_password: ""
ui_redis_host: ""
ui_redis_port: "{{ oilscope_config.services.redis.port }}"
ui_redis_database: "{{ oilscope_config.services.redis.database }}"
ui_health_retries: 30
ui_health_delay: 2
ui_docker_config_dir: /run/oilscope/docker-auth
ui_history_port: "{{ oilscope_config.services.history.port }}"
