# SPDX-License-Identifier: GPL-2.0-or-later
---
bastion_ssh_port: >-
  {{ (lookup('ansible.builtin.file', project_config_path) | from_json)
     .vms.bastion.ssh_port | int }}

ansible_port: "{{ bastion_ssh_port }}"
