# SPDX-License-Identifier: GPL-2.0-or-later
---
oilscope_bastion_address: "{{ hostvars[groups['bastion'][0]].ansible_host }}"
oilscope_bastion_ssh_port: "{{ hostvars[groups['bastion'][0]].ansible_port }}"

oilscope_bastion_private_key_file: >-
  {{ lookup('ansible.builtin.env', 'ANSIBLE_PRIVATE_KEY_FILE')
     | default('', true) }}

ansible_ssh_common_args: >-
  {{ oilscope_ssh_base_args }}
  -o ProxyCommand="ssh -W %h:%p -q
  -p {{ oilscope_bastion_ssh_port }}
  {{ oilscope_ssh_base_args }}
  {% if oilscope_bastion_private_key_file | length > 0 %}
  -o IdentitiesOnly=yes
  -i {{ oilscope_bastion_private_key_file | quote }}
  {% endif %}
  {{ ansible_user }}@{{ oilscope_bastion_address }}"
