# SPDX-License-Identifier: GPL-2.0-or-later
---
oilscope_bastion_group: "{{ oilscope_cloud }}_bastion"
oilscope_bastion_host: "{{ groups.get(oilscope_bastion_group, []) | first }}"
oilscope_bastion_address: "{{ hostvars[oilscope_bastion_host].ansible_host }}"
oilscope_bastion_ssh_port: >-
  {{ hostvars[oilscope_bastion_host].oilscope_bastion_ssh_port }}

ansible_ssh_common_args: >-
  {{ oilscope_ssh_base_args }}
  -o ProxyCommand="ssh -W %h:%p -q
  -p {{ oilscope_bastion_ssh_port }}
  -i {{ ansible_ssh_private_key_file }}
  {{ oilscope_ssh_base_args }}
  {{ ansible_user }}@{{ oilscope_bastion_address }}"
