# SPDX-License-Identifier: GPL-2.0-or-later
---
galaxy_info:
  role_name: redis
  author: Push and Pray team
  description: Deploy Redis for OilScope.
  license: GPL-2.0-or-later
  min_ansible_version: "2.16"
dependencies: []
